spring :
    servlet :
        multipart :
            max-file-size :    10MB
            max-request-size : 10MB
    datasource :

        # PostgreSQL
        url :      jdbc:postgresql://localhost:5432/tradesuite
        #

        # MySQL
#        url :      jdbc:mysql://localhost:3306/tradesuite
        #

        username : postgres
        password : postgres
    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true

        # PostgreSQL
        properties :
            hibernate :
                dialect : org.hibernate.dialect.PostgreSQLDialect
                jdbc :
                    lob :
                        non_contextual_creation : true
        #

server :
    port : 8080
